name: Build
on:
  push:
    tags:
      - 'v*'  # vから始まるタグがプッシュされたら実行

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies (ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev
      - uses: oven-sh/setup-bun@v1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: |
          bun install
          bun tauri build
      - uses: softprops/action-gh-release@v2
        with:
          files: src-tauri/target/release/bundle/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
